[tool.ruff.format]
# Use single quotes rather than double quotes.
# Double quotes are preserved for triple quotes (eg. doc-strings).
quote-style = "single"

[tool.mypy]
warn_unused_configs = true
disallow_incomplete_defs = true
mypy_path = "./src"

# Blacklist modules without type stubs
[[tool.mypy.overrides]]
module = ['packagewithoutstubs']
ignore_missing_imports = true
